### ISSUE TITLE
Site Down

### ISSUE THREAD

**Issue by ghost** [StefanRudvin/HipsterGramTDD#2]
Wasn't sure if you knew that your site isn't loading.

**Comment by StefanRudvin** [comment]
Hi, yes as this is just a hobby project I've closed the domain for something else. Thanks for letting me know!

**Comment by ghost** [comment]
Hey Stefan, honestly how well does this work, I might like to fork it and continue the development?

**Comment by StefanRudvin** [comment]
Hi 19peaches, the project works well with the basic Instagram features such as posting pictures, likes etc. Keep in mind it is a hobby project, so there will be bugs. Go ahead and continue development, great that the project gets some use! I am busy with University and work at the moment, but do let me know if there's anything I can help with.
